In [3]:
import numpy as np

def simple_operation(a):
    print(a,"\n")
    print(a.ndim,"number of dimension")
    print(a.size,"total size of array")
    print(a.shape,"size of each dimension")
    print(a.dtype," data type of array")
    print(a.itemsize,"list the size(in Byte) each array elements")
    print(a.nbytes, "list the total size array in Byte")


In [4]:
print("\n 1D \n")
a=np.array([1,2,3,4])      #  1D array
simple_operation(a)



 1D 

[1 2 3 4] 

1 number of dimension
4 total size of array
(4,) size of each dimension
int32  data type of array
4 list the size(in Byte) each array elements
16 list the total size array in Byte


In [5]:
print("\n 2D \n")
b=np.array([[1,2,3,4],[5,6,7,8] ])    # 2D array
simple_operation(b)




 2D 

[[1 2 3 4]
 [5 6 7 8]] 

2 number of dimension
8 total size of array
(2, 4) size of each dimension
int32  data type of array
4 list the size(in Byte) each array elements
32 list the total size array in Byte


In [6]:
print("\n 2D array",b)
print(b.reshape(4,2))

x=np.array([1,2,3,4])
print(x.itemsize)



 2D array [[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
4


In [7]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x.itemsize)



1
