In [2]:
import numpy as np

def simple_operation(a):
    print(a,"\n")
    print(a.ndim,"number of dimension")
    print(a.size,"total size of array")
    print(a.shape,"size of each dimension")
    print(a.dtype," data type of array")
    print(a.itemsize,"list the size(in Byte) each array elements")
    print(a.nbytes, "list the total size array in Byte")


In [3]:
print("\n 1D \n")
a=np.array([1,2,3,4])      #  1D array
simple_operation(a)



 1D 

[1 2 3 4] 

1 number of dimension
4 total size of array
(4,) size of each dimension
int32  data type of array
4 list the size(in Byte) each array elements
16 list the total size array in Byte


In [4]:
print("\n 2D \n")
b=np.array([[1,2,3,4],[5,6,7,8] ])    # 2D array
simple_operation(b)




 2D 

[[1 2 3 4]
 [5 6 7 8]] 

2 number of dimension
8 total size of array
(2, 4) size of each dimension
int32  data type of array
4 list the size(in Byte) each array elements
32 list the total size array in Byte


In [5]:
print("\n 2D array",b)
print(b.reshape(4,2))

x=np.array([1,2,3,4])
print(x.itemsize)



 2D array [[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
4


In [6]:
x=np.array([1,2,3,4],dtype=np.int8)
print(x.itemsize)



1


In [7]:
# EMPTY
#It creates an uninitialized array of specified shape and dtype.
#numpy.empty(shape, dtype = float, order = 'C')

x = np.empty([3,2], dtype =np.int)
print(x)


[[ 170685550  538976288]
 [ 538976288 2019893280]
 [1953523043 1634235424]]


In [12]:
#Zeros
#it return the array of specific size filled with Zeros
#numpy.zeros(shape, dtype = float, order = 'C')

x=np.zeros([2,3],dtype=np.int)
print(x)

[[0 0 0]
 [0 0 0]]


In [13]:
# Ones
#it return array of specific size filled with Ones
#numpy.ones(shape, dtype = None, order = 'C')

x = np.ones([2,2], dtype = int)
print(x)



[[1 1]
 [1 1]]


In [14]:
#  arange
#This function returns an ndarray object containing evenly spaced values within a given range.
#numpy.arange(start, stop, step, dtype)

x = np.arange(10,20,2)
print( x)



[10 12 14 16 18]
